import pandas as pd
import io

# 這是完整的題目資料
csv_content = """id,topic,question_text,image_filename,option_a,option_b,option_c,option_d,correct_answer,explanation
1,Separation Methods,Which of the following mixtures can be separated by filtration?,,"a mixture of oil and water","a mixture of ethanol and water","a mixture of silver chloride and water","a mixture of sodium chloride and water",C,"Filtration is used to separate an insoluble solid from a liquid. Silver chloride (AgCl) is insoluble in water, whereas NaCl is soluble."
2,Environmental Chem,Which of the following gases can cause acid rain?,,"CH4(g)","CO(g)","N2(g)","SO2(g)",D,"Sulphur dioxide (SO2) dissolves in rain water to form sulphurous acid (and eventually sulphuric acid), causing acid rain. CH4 is a greenhouse gas; CO is toxic; N2 is inert."
3,General Chem,Solid W dissolves in water to form an alkaline solution. What is W?,,"calcium oxide","calcium chloride","copper(II) oxide","copper(II) chloride",A,"Calcium oxide (CaO) is a basic oxide that reacts with water to form calcium hydroxide, Ca(OH)2, which is alkaline. Copper oxides/chlorides are insoluble or acidic."
4,Stoichiometry,"The table shows molar masses of four fertilisers. Which has the highest percentage by mass of nitrogen? (N=14.0)",,"(NH2)2CO","NH4NO3","NaNO3","(NH4)2SO4",A,"Calculate %N: Urea (NH2)2CO = 28/60 (46.7%); NH4NO3 = 28/80 (35%); NaNO3 = 14/85 (16.5%); (NH4)2SO4 = 28/132 (21.2%). Urea is highest."
5,Redox,"Consider the experimental set-up with KMnO4 and CuSO4. What is observed after the circuit is closed?",2023_q5_setup.png,"Purple patch and blue patch migrate to P","Purple patch and blue patch migrate to Q","Purple to P, Blue to Q","Purple to Q, Blue to P",C,"MnO4- ions are purple and negative (anions), so they migrate to the positive electrode (Anode, P). Cu2+ ions are blue and positive (cations), so they migrate to the negative electrode (Cathode, Q)."
6,Stoichiometry,"Metal X is less reactive than silver. 2.21 g of oxide of X is heated to leave 1.97 g solid. What is the formula of the oxide? (O=16, X=197)",,"XO","XO2","X2O","X2O3",D,"Mass of O = 2.21 - 1.97 = 0.24g. Moles O = 0.24/16 = 0.015. Moles X = 1.97/197 = 0.01. Ratio X:O = 0.01:0.015 = 2:3. Formula is X2O3."
7,Acids & Bases,Which statement concerning aqueous ammonia is INCORRECT?,,"It is a weak alkali","Concentrated aqueous ammonia is corrosive","It can distinguish between Pb(NO3)2 and Al(NO3)3","When added to CuSO4 until excess, a deep blue solution forms",C,"Both Pb2+ and Al3+ form white precipitates with ammonia that are insoluble in excess ammonia. Therefore, ammonia cannot distinguish between them (unlike NaOH)."
8,Energetics,Which of the following is endothermic?,,"dilution of concentrated sulphuric acid","thermal decomposition of limestone","reaction of quicklime with water","combustion of ethanol",B,"Thermal decomposition requires heat energy to break bonds (CaCO3 -> CaO + CO2), so it is endothermic. The others release heat (exothermic)."
9,Organic Chem,Which equation represents cracking of C16H34 to give propene?,,"C16H34 -> C2H4 + C7H14 + C7H16","C16H34 -> C3H6 + C6H12 + C7H14","C16H34 -> C3H6 + C6H14 + C7H14","C16H34 -> C3H8 + C5H10 + C8H16",C,"We need propene (C3H6) as a product. Equation C produces C3H6 and the number of atoms balance: Carbon 3+6+7=16; Hydrogen 6+14+14=34."
10,Fossil Fuels,"Petroleum separation: Fraction U (upper) vs Fraction L (lower). Which statement is correct?",,"U has higher boiling range & viscosity than L","U has higher boiling range & lower viscosity than L","U has lower boiling range & higher viscosity than L","U has lower boiling range & lower viscosity than L",D,"Upper fractions (U) have smaller molecules, lower boiling points, and are less viscous (runnier) than lower fractions (L)."
11,Redox/Cells,"Consider the three chemical cells shown. What is the descending order of reactivity of metals P, Q, and R?",2023_q11_cell.png,"P > Q > R","P > R > Q","R > P > Q","Q > R > P",B,"(Based on standard diagram) Electrons flow from more reactive to less reactive. If P donates to Q/R, P is strongest. Order P > R > Q typically follows voltage magnitude."
12,Energetics,"40cm3 0.5M HCl + 40cm3 0.5M NaOH gives rise of ΔT. What is the rise for 60cm3 1.0M HCl + 60cm3 0.5M NaOH?",,"0.75 ΔT","1.0 ΔT","1.5 ΔT","2.0 ΔT",B,"In Exp 1, conc of reacting ions is proportional to 0.5M. In Exp 2, OH- is limiting (0.5M), so the amount of heat generated per unit volume is the same. The temp rise remains 1.0 ΔT."
13,Electrolysis,"Which combination concerning electrolysis of copper(II) sulphate solution is correct?",2023_q13_table.png,"Cathode: graphite, Observation: Reddish brown solid on anode","Cathode: graphite, Observation: Mass of cathode decreases","Cathode: copper, Observation: Blue colour fades","Cathode: copper, Observation: Mass of anode decreases",D,"Using copper electrodes: The anode dissolves (Cu -> Cu2+ + 2e-), so its mass decreases. The cathode gains mass. The solution colour stays blue."
14,Stoichiometry,"0.729 g Mg reacts with 50.0 cm3 0.50 M H2SO4. What is the mass of Mg remaining? (Mg=24.3)",,"0.122 g","0.243 g","0.425 g","0.608 g",A,"Moles Mg = 0.03. Moles H2SO4 = 0.025. Ratio 1:1. H2SO4 is limiting. Mg reacted = 0.025. Mg left = 0.005 mol. Mass left = 0.005 * 24.3 = 0.122g."
15,Bonding,Argon is a gas at room temperature and pressure because...,,"outermost shell has octet structure","attractive force between atoms is weak","molecules are monoatomic","argon is chemically inert",B,"Physical state (solid/liquid/gas) is determined by intermolecular forces. Argon atoms have very weak van der Waals' forces between them."
16,Redox,"Reaction: Cl2 + 2Br- -> Br2 + 2Cl-. Which statement about the oxidising agent is correct?",,"It loses electrons and is reduced","It gains electrons and is reduced","It loses electrons and is oxidised","It gains electrons and is oxidised",B,"The oxidising agent is Cl2. It takes electrons from Br- (gains electrons) and its oxidation number drops from 0 to -1 (is reduced)."
17,Bonding,"Which statements concerning ice and water are correct? (1) Ice has open structure. (2) H-bonds in ice is double that in water. (3) H2O in ice is tetrahedral, in water is V-shaped.",,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",A,"(1) is true (hexagonal open structure). (2) is false (water has fewer H-bonds, but not exactly half). (3) is false because H2O molecules are always V-shaped; only the arrangement is tetrahedral."
18,Bonding,"Properties of XBr and ZBr (see image/table). Which statements are correct?",2023_q18_table.png,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",A,"Usually refers to Ionic (X) vs Covalent (Z). XBr conducts when molten. ZBr is likely hydrolysed or insoluble. Only (1) fits standard patterns for Group 1 vs Group 14/15."
19,Organic Chem,"Members of homologous series of alkenes have the same... (1) structural formula (2) empirical formula (3) general formula",,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",D,"Homologous series have the same General Formula (CnH2n). Alkenes all have empirical formula CH2. They have DIFFERENT structural formulas."
20,Energetics,"Which statements are correct? (1) Formation of liquid N2 is not zero. (2) Formation of compound must be negative. (3) Formation of CO(g) can be determined directly.",,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",A,"(1) is true because standard state of N2 is gas, not liquid. (2) is false (can be endothermic). (3) is false (C + O2 forms CO2 mixture, cannot isolate CO easily)."
21,Corrosion,"Which set-ups prevent rusting of underground iron pipe?",2023_q21_setup.png,"(1) and (2) only","(1) and (3) only","(2) and (3) only","(1), (2) and (3)",A,"Sacrificial protection (connecting to Mg/Zn, more reactive) and Cathodic protection (connecting to negative terminal) work. Connecting to Copper (less reactive) accelerates rusting."
22,Acids & Bases,"Sol A (1M HNO3) vs Sol B (0.5M H2SO4). Which statements are correct? (1) Both react with Fe. (2) Require same vol of KOH for neutralisation. (3) Same moles of gas with CaCO3.",,"(1) and (2) only","(1) and (3) only","(2) and (3) only","(1), (2) and (3)",A,"Both are acids (react with Fe). Both have 1M H+ concentration (so same KOH needed). However, H2SO4 forms insoluble CaSO4 with limestone, stopping the reaction, so (3) is false."
23,Organic Chem,"Statements about ethanoic acid: (1) Present in vinegar. (2) Changes phenolphthalein to pink. (3) Is an alkanoic acid.",,"(1) and (2) only","(1) and (3) only","(2) and (3) only","(1), (2) and (3)",B,"Acids turn phenolphthalein colourless, not pink. (1) and (3) are true."
24,Organic Chem,"1st statement: Butane and methylpropane have same physical properties. 2nd: They have same molecular formula.",,"Both true, 2nd explains 1st","Both true, 2nd DOES NOT explain 1st","1st false, 2nd true","Both false",C,"They are isomers (same molecular formula), but isomers have different physical properties (BP/MP). So 1st is False, 2nd is True."
25,Kinetics,"Decomposition of H2O2. Exp I (1.0M, 25cm3) vs Exp II (0.5M, 50cm3). Which graph is correct?",2023_q25_graph.png,"Graph A","Graph B","Graph C","Graph D",A,"Same moles means same final volume of gas. Exp I has higher concentration (1.0M), so faster initial rate (steeper slope). Graph A shows steeper slope + same max height."
26,Stoichiometry,"Reaction: C3H8 + 5O2 -> 3CO2 + 4H2O. 100cm3 C3H8 burns in 600cm3 O2. Volume of resulting gas mixture?",,"800 cm3","700 cm3","400 cm3","300 cm3",C,"100 C3H8 reacts with 500 O2 to form 300 CO2. Remaining Gas = 100 unreacted O2 + 300 CO2 product = 400 cm3. (Water is liquid)."
27,Equilibrium,"Fe3+ + SCN- <=> Fe(SCN)2+. Add Fe(NO3)3. How does new equilibrium compare? (Conc of complex / Rate of backward)",,"decreased / unchanged","decreased / increased","increased / unchanged","increased / increased",D,"Adding Fe3+ shifts equilibrium to the right, increasing the concentration of the complex (red). Since Rate_bwd = k[Complex], the backward rate also increases."
28,Kinetics,Which reaction is fastest at room conditions?,,"AgNO3(aq) + NaCl(aq)","Zn(s) + 2HCl(aq)","4Fe(s) + 3O2(g)","CH4(g) + Br2",A,"Precipitation of AgCl involves simple ion attraction. It is virtually instantaneous. Others involve bond breaking/redox/covalent mechanisms which are slower."
29,Equilibrium,"Equilibrium constants K1 (HI dissociation) and K2 (HI formation). What is the relationship?",,"K1 = 1/K2","K1 = 1/(K2)^2","K2 = 1/(2K1)","K2 = 1/(K1)^2",A,"Dissociation: 2HI <=> H2 + I2. Formation: H2 + I2 <=> 2HI. The equations are exact reverses of each other. The equilibrium constant of a reverse reaction is the reciprocal (1/K)."
30,Organic Chem,Which pair would NOT react?,,"ethene + HCl","propan-1-ol + PCl3","propene + H2 (Pt catalyst)","methylpropan-2-ol + acidified K2Cr2O7",D,"Tertiary alcohols (like methylpropan-2-ol) cannot be oxidised by K2Cr2O7 because the carbon with the -OH group has no Hydrogen atom attached to remove."
31,Organic Chem,What is W in the conversion? (Reduction of ketone/aldehyde)",2023_q31_structure.png,"Option A","Option B","Option C","Option D",D,"(Based on standard synthesis) Converting a carbonyl group (C=O) to an alcohol (C-OH) is reduction. Reagents like LiAlH4 or NaBH4 are used."
32,Equilibrium,"X <=> Y. Equilibrium ratio X:Y is 1:3. Which statements correct? (1) Qc > Kc before eqm. (2) Starting with Y only gives same ratio. (3) Backward rate = 3x Forward rate.",,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",B,"(1) is false (if start with X, Qc < Kc). (3) is false (at eqm, rates are equal). (2) is true because Kc is a constant regardless of starting direction."
33,Periodic Table,"Elements across Period 2 (left to right). Which correct? (1) Carbon has highest mp. (2) Li has highest conductivity. (3) Bond type changes ionic to covalent.",,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",A,"(1) True (Diamond/Graphite). (2) False (Be often conducts better due to 2e- per atom, or Al in period 3). (3) False (Elements are Metallic -> Covalent, not Ionic)."
34,Organic Chem,"Structure shown. Which correct? (1) Soluble in water. (2) Has ester group. (3) Empirical formula CH2O.",2023_q34_structure.png,"(1) only","(2) only","(1) and (3) only","(2) and (3) only",C,"The structure has many -OH groups, making it soluble (1 True). No COO group (2 False). If it is a sugar/hexose, empirical formula is CH2O (3 True)."
"""

# 寫入正確的 UTF-8 格式
try:
    with open("questions.csv", "w", encoding="utf-8") as f:
        f.write(csv_content)
    print("✅ 成功！questions.csv 已經建立好了，格式完美。")
except Exception as e:
    print(f"❌ 發生錯誤: {e}")